server:
  port: '8081'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Packages to include
springdoc:
  packagesToScan: com.poc.academia.api.auth.controllers, 
                  com.poc.academia.api.aula.controllers,
                  com.poc.academia.api.pessoa.controllers

# AWS S3 configuration
aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  s3:
    bucket: images
    region: us-east-2