server:
  port: '8081'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970